name: Build and Deploy Frontend

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: |
        cd frontend
        rm -rf node_modules package-lock.json
        npm install

    - name: Build frontend
      run: |
        cd frontend
        npm run build

    - name: Deploy to dist branch
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      run: |
        # 配置Git用户信息
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        # 切换到dist分支（如果不存在则创建）
        git checkout --orphan dist || git checkout dist
        
        # 删除dist分支上的所有文件（除了.git）
        git rm -rf . || true
        
        # 复制构建文件到根目录
        cp -r frontend/dist/* .
        
        # 添加所有文件到Git
        git add .
        
        # 提交更改
        git commit -m "Deploy frontend build - $(date)"
        
        # 推送到dist分支
        git push origin dist --force 